version: '3'

services:
  php-web:
    build: docker/php-web
    container_name: php-web
    working_dir: /var/www
    environment: [ xdebug_remote_host=10.0.75.1 ] # for windows
    ports:
      - 10080:80
    links:
      - mysql
    volumes:
      - .:/var/www
  php-cli:
    build: docker/php-web
    container_name: php-cli
    working_dir: /var/www
    command: php -v
    links:
      - mysql
    volumes:
      - .:/var/www
  mysql:
    image: library/mysql:5.7
    container_name: mysql
    ports:
      - 13306:3306
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=oneforallallinone
